apiVersion: apps/v1
kind: Deployment
metadata:
  name: photosapplication-deployment
  labels:
    app: photos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
        - ports:
            - containerPort: 80
          name: photos-application
          image: bhuvanprasad/photosapp:v5899484607
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-cred
