apiVersion: apps/v1
kind: Deployment
metadata:
  name: photosapplication-deployment
  labels:
    app: photos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
        - ports:
            - containerPort: 80
          name: photos-application
          image: nginx:latest
          imagePullPolicy: Always
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c0a893eb0eda50bf
    volumeAttributes:
      encryptInTransit: "true"
