apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeName: efs-pva
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
